### PR TITLE
Add old PHPUnit

### LINKED ISSUE #6: Add old version of PHPUnit for PHP versions < 5.6

### PR DESCRIPTION
**Pull request by BronsonQuick**
Fixes #6

### CODE REVIEW

**Comment by rmccue** [comment]
I think we should maybe just always use `phpunit-old.phar`; IIRC the WP tests don't run properly with the new version anyway?

**Comment by BronsonQuick** [comment]
@rmccue Ahh okay then. Good call. Hang 5 and I'll remove the old one :+1:

**Comment by BronsonQuick** [comment]
@rmccue Updated and tested :smile: #reviewmerge

**Comment by rmccue** [comment]
> Hang 5

:surfer:

**Pull request merged**
